  services:
    postgres:
      image: cimg/postgres:18.0-postgis
      container_name: eventify-postgres
      restart: unless-stopped
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: app_development
      ports:
        - "6000:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - ci_network
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d app_development"]
        interval: 5s
        timeout: 3s
        retries: 20
    mongodb:
      image: mongo:8.0
      container_name: eventify-mongodb
      restart: unless-stopped
      ports:
        - "27021:27017"
      volumes:
        - mongo_data:/data/db
      networks:
        - ci_network
      environment:
        MONGO_INITDB_ROOT_USERNAME: mongodb
        MONGO_INITDB_ROOT_PASSWORD: mongodb
        MONGO_INITDB_DATABASE: app_development
      healthcheck:
        test: ["CMD", "mongosh", "--username=mongodb", "--password=mongodb", 
          "--authenticationDatabase=admin", "--eval", "db.adminCommand('ping')"]
        interval: 10s
        timeout: 5s
        retries: 5
      

  volumes:
    postgres_data:
    mongo_data:

  networks:
    ci_network:
      driver: bridge
