openapi: 3.0.1
info:
  title: Eventify API
  version: v1
servers:
  - url: http://localhost:7000
paths:
  /api/v1/events:
    get:
      summary: List events
      tags: [Events]
      responses:
        "200":
          description: OK
