source "https://rubygems.org"

ruby "3.4.5"

gem "rails", "~> 8.0"

gem "pg"

gem "mongoid", "~> 9.0"

gem "puma", ">= 5.0"

gem "activerecord-postgis-adapter"

# gem "jbuilder"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
gem "bcrypt", "~> 3.1.7"

gem "jwt"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Use the database-backed adapters for Rails.cache, Active Job, and Action Cable
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem "kamal", require: false

# Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]
gem "thruster", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem 'rack-cors', require: 'rack/cors'

gem "kaminari"
gem "rswag-api", "2.16.0"
gem "rswag-ui", "2.16.0"

group :development, :test do
  gem "dotenv-rails"

  gem "rubocop", require: false

  gem "rubocop-rails-omakase", require: false

  gem "rubocop-performance", require: false

  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", require: false

  gem "shoulda-matchers", "~> 6.0"

  gem "rspec-rails", "~> 8.0"

  gem "faker"
end
