name: RUBY-CI

on:
  push:
    branches: ["issue-*"]
    paths:
      - "api/**"
      - ".github/workflows/ci.yml"
      - "api/.rubocop*"
  pull_request:
    branches: [main, develop]
    paths:
      - "api/**"
      - ".github/workflows/ci.yml"
      - "api/.rubocop*"

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: api/.ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bundle exec brakeman --no-pager

  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: api/.ruby-version
          bundler-cache: true
        env:
          BUNDLE_GEMFILE: api/Gemfile

      - name: Lint code for consistent style
        run: bundle exec rubocop -f github

  # test:
  # runs-on: ubuntu-latest
#
# # services:
# #  redis:
# #    image: redis
# #    ports:
# #      - 6379:6379
# #    options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
# steps:
# - name: Install packages
# run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libyaml-dev pkg-config
#
# - name: Checkout code
# uses: actions/checkout@v4
#
# - name: Set up Ruby
# uses: ruby/setup-ruby@v1
# with:
# ruby-version: .ruby-version
# bundler-cache: true
#
# - name: Run tests
# env:
# RAILS_ENV: test
# # REDIS_URL: redis://localhost:6379/0
# run: bin/rails db:test:prepare test
